# Basic Configuration
baseURL = "/"
languageCode = "ru-ru"
title = "Сноска"
theme = "hugo-saasify-theme"

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
[module.hugoVersion]
extended = true
min = "0.140.0"

# Required Build Configuration
[build]
writeStats = true      # Required for TailwindCSS

# Required Markup Configuration
[markup]
[markup.highlight]
noClasses = false
lineNos = true
codeFences = true
[markup.goldmark.renderer]
unsafe = true       # Allow HTML in markdown
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

# Theme Parameters
[params]
description = "Автоматическая маркировка иноагентов, террористов, экстремистов"
author = "dev366.com"
logo = "/images/logo.svg"      # Path to your logo
# Google Analytics ID (e.g., "G-XXXXXXXXXX")
googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production

# Header Configuration
[params.header]
background = "bg-white/80 backdrop-blur-sm"
border = "border-b border-gray-100"

# Header Logo
[params.header.logo]
src = "/images/logo.svg"

# Header Buttons (optional)
[params.header.buttons]
[params.header.buttons.signIn]
text = "Войти в ЛК"
url = "/signin"
[params.header.buttons.getStarted]
text = "Подключиться"
url = "/get-started"

# Global CTA Configuration (optional)
[params.cta]
enable = true
title = "Готовы подключиться?"
#description = "Join companies using our platform"
[params.cta.primary_button]
text = "Да, подключаемся"
url = "/get-started"
[params.cta.secondary_button]
text = "Нет, хочу задать вопрос"
url = "mailto:info@snoska.media?subject=Вопрос"

# Social Media Links (optional)
[params.social]
#linkedin = "https://linkedin.com/in/yourusername"
#twitter = "https://twitter.com/yourusername"
#github = "https://github.com/yourusername"
telegram = "https://t.me/snoska_media"

# Navigation Menu
[menu]
[[menu.main]]
name = "Главная"
weight = 1
url = "/"

[[menu.main]]
name = "Цены"
url = "/pricing"
weight = 2
[[menu.main]]
name = "Вопросы и ответы"
url = "/blog"
weight = 3
#[menu.main.params]
#has_submenu = true
#submenu = [
#  { name = "Feature 1", url = "/features/feature-1/" },
#  { name = "Feature 2", url = "/features/feature-2/" }
#]

#[[menu.main]]
#name = "Blog"
#url = "/blog"
#weight = 3
#[[menu.main]]
#name = "Company"
#weight = 4
#[menu.main.params]
#has_submenu = true
#submenu = [
#  { name = "About Us", url = "/company/" },
#  { name = "Careers", url = "/careers/" }
#]

# Footer Column 1 Menu
[[menu.footer_column_1]]
name = "О Нас"
url = "/company"
weight = 2
[[menu.footer_column_2]]
name = "Правила"
url = "/terms"
weight = 1
[[menu.footer_column_3]]
name = "Политика"
url = "/privacy"
weight = 1
#[[menu.footer_column_1]]
#name = "Design System"
#url = "/features/design-system/"
#weight = 2
#[[menu.footer_column_1]]
#name = "Developer Experience"
#url = "/features/developer-experience/"
#weight = 3

# Footer Column 2 Menu
#[[menu.footer_column_2]]
#name = "Blog"
#url = "/blog"
#weight = 1
#[[menu.footer_column_2]]
#name = "О Нас"
#url = "/company"
#weight = 2
#[[menu.footer_column_2]]
#name = "Careers"
#url = "/careers"
#weight = 3

